myshop02/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('shop.urls', namespace='shop')),
    
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

shop/urls.py
from django.urls import path
from . import views 

app_name='shop'

urlpatterns =[
    path('', views.product_list, name='product_list'),
    path('<slug:category_slug>/', views.product_list, name='product_list_by_category'),
    path('<int:id>/<slug:slug>/', views.product_detail, name='product_detail'),
]

shop/models.py
from django.db import models
from django.urls import reverse

class Category(models.Model):
    name= models.CharField(max_length=200, db_index=True)
    slug= models.SlugField(max_length=200, unique=True)
    
    class Meta:

        ordering=('name',)
        verbose_name='category'
        verbose_name_plural='categories'

    def __str__(self):
        return self.name
    
    def get_absolute_url(self):
        return reverse('shop:product_list_by_category',args=[self.slug])

class Product(models.Model):
    
    category=models.ForeignKey(Category, related_name='products', on_delete=models.CASCADE)
    name= models.CharField(max_length=200, db_index=True)
    slug = models.SlugField(max_length=200, db_index=True)
    imagem=models.ImageField(upload_to='products/%y/%m/%d', blank='True')
    description=models.TextField(blank=True)
    price=models.DecimalField(max_digits=10, decimal_places=2)
    available=models.BooleanField(default=True)
    created=models.DateTimeField(auto_now_add=True)
    updated=models.DateTimeField(auto_now=True)

    class Meta:
        ordering =('name',)
        index_together=(('id','slug'),)

    def __str__(self):
        return self.name
    

    def get_absolute_url(self):
        return reverse('shop:product_detail', args=[self.id, self.slug])

shop/views.py
from django.shortcuts import get_object_or_404, render
from .models import Category, Product

def product_list(request, category_slug=None):
    category = None
    categories = Category.objects.all()
    products = Product.objects.filter(available=True)
    if category_slug:
        category = get_object_or_404(Category, slug=category_slug)
        products = products.filter(category=category)
    return render(request, 'shop/product/list.html', {'category':category,'categories':categories,'products':products})


def product_detail(request, id, slug):
    product =get_object_or_404(Product, id=id, slug=slug, available=True)
    return render(request, 'shop/product/detail.html', {'product':product})

shop/templates/shop/base.html
{% load static %}
<!DOCTYPE html>
<html lang="pt-BR">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="{% static 'css/style.css' %}">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous"> 
   
</head>
<body>
    <div class="container">
    <div id="">
        <br>
        <h1 style="font-size: 50px;">Alfa Roupas</h1>
    </div>
    <div style=" margin:0 auto; width:0 auto; height:70px; background:#020d3f;">
        <div style="font-size: 20px; margin-left: 850px; color:white;">Seu carrinho está vazio.</div>
    </div>

         {% block content %}
         {% endblock%}
    
    </div> 
   <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM" crossorigin="anonymous"></script>
</body>
</html>

shop/templates/shop/product/detail.html
{% extends 'shop/base.html' %}
{% load static %}


{% block content %}



<br>
<nav aria-label="breadcrumb">
    <ol class="breadcrumb">
       <li class="breadcrumb-item"><a href="/">Home</a></li>
       <li class="breadcrumb-item active" aria-current="page">{{ product.name }}</li>
    </ol>
</nav>
<hr>
<div class="row">
    <div class="col-12">
        <div class="row">
            <div class="col-2"><img src="{% if product.imagem %}{{ product.imagem.url }}{% else %}{% static 'img/no_imagem.jpg' %}{% endif %}"></div>
            <div class="col-6">
                <h1 style="margin-left: 15px; margin-top:15px;">{{ product.name }}</h1>
                <a href="{{ product.category.get_absolute_url }}"></a>
                <h2 style="margin-left: 15px; margin-top:15px;">{{product.category}}</h2>
                <p style="margin-left: 15px; margin-top:15px;">
                    R$ {{ product.price }}
                    <br>
                   
                </p>
                 <p style="margin-left: 15px; margin-top:15px;"> {{ product.description }}</p> 
            </div>
        </div>
    </div>
</div>

<div style="height:50px;">
   <div>
    
   </div>
    
   
</div>
{% endblock %}

shop/templates/shop/product/list.html
{% extends 'shop/base.html' %}
{% load static %}

{% block title %}
{% if category %}{{category.name}}{% else %}Products{% endif %}
{% endblock %}
  
</head>
<body>
    {% block content %}


<div class="row">
    <div class="col-12">
        <div class="row">
            <div class="col-4">
                
                    <div class="sidebar">
                       <h3>Categories</h3>
                       <ul>
                            <li {%if not category %}class="selected"{% endif %}>
                                <a href="{% url 'shop:product_list' %}">Todos</a>
                            </li>
                                {% for c in categories %}
                            <li {% if category.slug == c.slug %}class="selected"{% endif %}>
                                <a href="{{ c.get_absolute_url }}">{{c.name}}</a>
                            </li>
                                {% endfor %}
                        </ul>
                    </div>
            </div>
            <div class="col-8">
                <div class="row">
                   
                        <h1>
                        {% if category %}
                            {{ category.name }}
                        {% else %}
                            Produtos
                        {%endif%}
                        </h1>

                </div>
                    {% for product in products %}
                      
                        <a href="{{product.get_absolute_url}}">
                        <img src="{% if product.imagem %}{{ product.imagem.url }}{% else %}{% static 'img/no_imagem.jpg' %}{% endif %}">
                        <br>

                        {{ product.name }}
                         </a>
                        <a href="{{ product.get_absolute_url }}"></a>
                        <br>
                        R${{ product.price}}
                        <hr>
                    {% endfor %}
            </div>
        </div>
    </div>
</div>




    {% endblock %}
</body>
</html>